### ISSUE TITLE
[Suggestion] csv of suburb names and their corresponding calendar area names

### ISSUE THREAD

**Issue by benvalkin** [beyarkay/eskom-calendar#61]
I think it would be useful to compile a list of suburb names and their corresponding loadshedding area names (as they appear on the calendar list). Something as simple as this:
![image](https://user-images.githubusercontent.com/69928007/190927790-c4bffed1-a852-4f00-b823-edcc3306c688.png)

This would be good to aid location lookups for each calendar since it's often difficult to know what schedule your suburb belongs to. Plus it would be cool to have a a single open source data file for this information (which is usually displayed on separate municipal websites such as [this one](https://www.ekurhuleni.gov.za/wp-content/uploads/2021/11/Ekurhuleni-Load-Shedding-Schedule.pdf))

Compiling such a .csv file would be a once off task and not too tedious. Most suburb block information is posted in PDFs or spreadsheets in some form.
![image](https://user-images.githubusercontent.com/69928007/190927851-5a705220-b094-437f-8411-c196279e486c.png)

I'd be happy to manually compile one and put it on this repo if it would be useful (kinda want to do it for myself anyway)

**Comment by beyarkay** [comment]
Ben and I chatted in person about this. In summary:

- Definitely a good idea, and should be implemented
- Ideal format would be a yaml file containing a list of objects, each object defining one instance.

Example yaml file:
```yaml
# Calendar name is the name as seen on the releases page.
- calendar_name: city-of-cape-town-area-15
  province: western-cape
  municipality: city-of-cape-town
  area_name: city-of-cape-town
  block_name: 15
  # Since one calendar can be associated with multiple suburbs, add a 
  # list of possible aliases which the user might want to search for when 
  # looking for this calendar
  aliases: [rosebank, observatory, maitland, salt-river, woodstock, ...]
- calendar_name: city-of-cape-town-area-5
  province: western-cape
  municipality: city-of-cape-town
  area_name: city-of-cape-town
  block_name: 5
  aliases: [newlands, claremont, landsdowne, rondebosch-east, ...]
```
