### ISSUE TITLE
Allow more granular loadshedding specification

### ISSUE THREAD

**Issue by beyarkay** [beyarkay/eskom-calendar#62]
Currently it's only possible to specify one loadshedding schedule for the entire country, but this isn't ideal because quite often cape town will be on a different schedule. This change would change the specification of the `manually_specified.yaml` file to allow an optional "include_regex: XXX" and "exclude_regex: XXXX" to specify which areas the change would apply to. For example:

```yaml
  - stage: 6
    start: 2022-09-18T04:16:00
    finsh: 2022-09-20T23:59:00
    source: https://twitter.com/Eskom_SA/status/1571328907005120513
    include_regex: city-of-cape-town-area-.*

  - stage: 4
    start: 2022-09-18T04:16:00
    finsh: 2022-09-20T23:59:00
    source: https://twitter.com/Eskom_SA/status/1571328907005120513
    exclude_regex: city-of-cape-town-area-.*
```

This could get a bit tiresome, so a shorthand `include: XXX` and `exclude:XXX` would also be nice. So instead of specifying the full regex as above, you could just do:

```yaml
  - stage: 6
    start: 2022-09-18T04:16:00
    finsh: 2022-09-20T23:59:00
    source: https://twitter.com/Eskom_SA/status/1571328907005120513
    exclude: coct

  - stage: 4
    start: 2022-09-18T04:16:00
    finsh: 2022-09-20T23:59:00
    source: https://twitter.com/Eskom_SA/status/1571328907005120513
    include: coct
```

But then it also gets a bit tiresome to have to specify both the inclusion and the exclusion, so maybe there's a way to only use the most specific schedule?
